import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { ClerkProvider, SignedIn, SignedOut } from '@clerk/nextjs'

import { FaHome } from "react-icons/fa";
import { NavbarDemo } from "./(Navigation)/page";
import { Footer } from "@/components/common/footer";
import SideBar from "@/components/common/sidebar";

const navItems = [
    {
      name: "Home",
      link: "/",
      icon: <FaHome className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },
   
  ];
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider >
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavbarDemo />
          {children}
         <SignedOut >
           <Footer />
         </SignedOut>
      </body>
    </html>
    </ClerkProvider>
  );
}
